name: Deploy to Fly.io

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP_NAME: enion

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: Deploy to Fly.io
        run: |
          cd enion-cljs
          npm install
          npm run release
          cp -r resources ../enion-backend
          cd ../enion-backend
          lein uberjar
          flyctl deploy --remote-only  
